/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef AREA_TMP_DATA_H_
#define AREA_TMP_DATA_H_
#include "../defines.h"
#include "../typedefs.h"
#include <list>

struct	area_tmp_data
{
	std::list<MID*> mobs;
	std::list<OID*> objs;
	std::list<RID*> rooms;
	std::list<SHD*> shops;
	std::list<RHD*> repairs;
};

#endif //AREA_TMP_DATA_H_

