/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef CHAPTER_DATA_H_
#define CHAPTER_DATA_H_
#include "../defines.h"
#include "../typedefs.h"
#include <list>

struct chapter_data
{
	CHAPTER_INDEX_DATA	* pIndexData;
	std::list<QUEST_CMND_DATA*> init_cmds;
	std::list<QUEST_ACTION_DATA*> actions;
	std::list<EVENT_DATA*> events;
	int					nr;
	bool				completed;
};

#endif //CHAPTER_DATA_H_

