/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef CLAN_DATA_H_
#define CLAN_DATA_H_
#include "../defines.h"
#include "../typedefs.h"
#include <list>

struct	clan_data
{
	/* common members */
	std::list<MEMBER_DATA*> member_list;
	MEMBER_DATA			* leader;
	MEMBER_DATA			* first;
	MEMBER_DATA			* second;
	std::list<LAST_DATA*> ctalk_history;
	clan_type			type;
	char				* filename;
	char				* name;
	char				* description;
	char				* rank[CLAN_LEADER+1];
	int					clan_id;
	int64				flags;
	long				penalty;
	/* organization members */
	std::list<CLAN_DATA*> suborgs;
	CLAN_DATA			* mainorg;
	CLAN_DATA			* vClan;	//Trog: do votingu politycznego
	std::list<HQ_DATA*> hqs;
	std::list<POLITICS_DATA*> politics;
	MEMBER_DATA			* diplomat;
	char				* vYes; //Trog: do votingu politycznego (vno sie doda w przyszlosci)
	int					vRelations;	//Trog: do votingu politycznego
	char				* tmpstr;
	long				loan;
	time_t				repay_date;
	/* organization stats */
	int					vehicles;
	int					spacecrafts;
	int					branches; /* filie HQ razem z glowna */
	/* common stats */
	int					members;
	long				funds;
	int					pkills;
	int					pdeaths;
	int					mkills;
	int					mdeaths;
};

#endif //CLAN_DATA_H_

