/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef DIALOG_NODE_H_
#define DIALOG_NODE_H_
#include "../defines.h"
#include "../typedefs.h"
#include <list>

struct dialog_node
{
	/*! wska�nik na strukture ca�ego dialogu */
	DIALOG_DATA			* pBase;

	std::list<DIALOG_NODE*> children;
	/*! program kt�ry ma zadecydowa� czy pokaza� ten tekst */
	MPROG_DATA			* prog;
	/*! tekst jaki mo�emy skierowa� do moba */
	char				* text;
	char				* mob_answer;
	/*! nr porz�dkowy tej struktury w liscie */
	int					nr;
	/*! nr docelowy struktury - etapu do jakiej kieruje nas ten tekst */
	int					target_nr;
	bool				saved;
};

#endif //DIALOG_NODE_H_

