/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef DIALOG_DATA_H_
#define DIALOG_DATA_H_
#include "../defines.h"
#include "../typedefs.h"
#include <list>

struct dialog_data
{
	std::list<DIALOG_NODE*> nodes;
	char				* name; //nazwa dla danego dialogu
	int					dialog_ID;
};

#endif //DIALOG_DATA_H_

