/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef INFORM_DATA_H_
#define INFORM_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct inform_data
{
	char				* victim;
	char				* attacker;
	time_t				time;
	bool				reported;/* Je�li ofiara poskar�y si� na go�cia
					kt�rego nie ma w grze */
};

#endif //INFORM_DATA_H_

