/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef PLANET_DATA_H_
#define PLANET_DATA_H_
#include "../defines.h"
#include "../typedefs.h"
#include <list>

struct	planet_data
{
	std::list<GUARD_DATA*> guards;
	SPACE_DATA			* starsystem;
	std::list<AREA_DATA*> areas;
	CLAN_DATA			* governed_by;
	std::list<DOCK_DATA*> docks;
	char				* name;
	char				* filename;
	long				base_value;
	int					population;
	int64				flags;
	float				pop_support;
	int					first_jail;//added by Thanos (wi�zienia na planetach)
	int					last_jail;
	int					import;
	int					_export;
	int					prisei;
	int					prisee;
	int					stock;
	int					maxstock;
	float				xpos;//added by Aldegard (zamieniamy all na listy)
	float				ypos;
	float				zpos;
	float				gravity;
	int					version;//
	char				* description;
	char				* description2;
	std::list<SEASON_DATA*> seasons;
	SEASON_DATA			* curr_season;	/* Thanos */
	int					daylen;		/* domy�lna d�ugo�� dnia */
	int					nightlen;	/* domy�lna d�ugo�� nocy */
	int					monthlen;	/* domy�lna d�ugo�� miesi�ca */
	int					hour;		/* aktualna godzina */
	int					day;		/* aktualny dzien */
	int					month;		/* aktualny miesiac */

	int					mmhg;		/* cisnienie */
	int					change;		/* zmiana cisnienia */
	int					sky;		/* jakie niebo */
	int					sunlight;	/* jakie slonce */
	int					windspeed;	/* predkosc wiatru */
	int					winddir;	/* kierunek wiatru */
	int					temperature;	/* done */
	float				radius;
	float				star_radius;
	float				star_radius2;
	std::list<DEPOSIT_DATA*> deposits;
	WAREHOUSE_DATA		* pWarehouse;
};

#endif //PLANET_DATA_H_

