/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef QUEST_DATA_H_
#define QUEST_DATA_H_
#include "../defines.h"
#include "../typedefs.h"
#include <list>

struct	quest_data
{
	QUEST_INDEX_DATA	* pIndexData;
	std::list<CHAPTER_DATA*> chapters;
	CHAPTER_DATA		* curr_chapter;
	std::list<QUEST_MOB_DATA*> mobs;
	std::list<QUEST_OBJ_DATA*> objs;
	CHAR_DATA *			player;
	bool				finished;
	bool				failed;		/*czy si� nie sko�czy� za czas*/
	time_t				logon;		/*o kt�rej zosta� odpalony/wznowiony*/
	int					time_took;	/*ile zaj�� przedtem czasu */
	int					curr_qp;
	std::list<QUEST_CMND_DATA*> init_cmds;
	std::list<QUEST_ACTION_DATA*> actions;
};

#endif //QUEST_DATA_H_

