/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef ROOM_INDEX_DATA_H_
#define ROOM_INDEX_DATA_H_
#include "../defines.h"
#include "../typedefs.h"
#include <list>

struct	room_index_data
{
	SHIP_DATA			* ship;		//Thanos
	std::list<CHAR_DATA*> people;
	std::list<OBJ_DATA*> contents;
	std::list<EXTRA_DESCR_DATA*> extradesc;
	AREA_DATA			* area;
	std::list<EXIT_DATA*> exits;
	std::list<SHIP_DATA*> ships;
	std::list<RESET_DATA*> resets;
	VAR_DATA			* variables; /* Ratm - zmienne do mob_programow */
	char				* name;
	char				* homename;
	char				* description;
	char				* nightdesc;
	int					vnum;
	int					svnum;			/* Thanos: constrship */
	int64				room_flags;
	MPROG_ACT_LIST		* mpact;	       /* mudprogs */
	int					mpactnum;	     /* mudprogs */
	std::list<MPROG_DATA*> mudprogs;	       /* mudprogs */
	int64				progtypes;	     /* mudprogs */
	int					mpscriptrun;		/* Thanos - latwiej szuka� proga */
	int					light;
	int					sector_type;
	int					tele_vnum;
	int					tele_delay;
	int					tunnel;		/* max people that will fit */
	/* Trog: clan stuff */
	HQ_ROOM				clan_room;
};

#endif //ROOM_INDEX_DATA_H_

