/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef SPACE_DATA_H_
#define SPACE_DATA_H_
#include "../defines.h"
#include "../typedefs.h"
#include <list>

struct space_data
{
	std::list<SHIP_DATA*> ships;
	std::list<ASTRO_DATA*> astros;
	std::list<MISSILE_DATA*> missiles;
	std::list<PLANET_DATA*> planets;
	std::list<STAR_DATA*> stars;
	std::list<MOON_DATA*> moons;
	std::list<RESET_DATA*> resets;
	char				* filename;
	char				* name;
	char				* resetmsg;		// Thanos
	int					age;			// Thanos
	int					reset_frequency;// Thanos
	float				xpos;
	float				ypos;
	int					crash;
	int					hidden;
	int					version;
	char				* description;
	char				* description2;
	char				* description3;
	int64				flags;
};

#endif //SPACE_DATA_H_

