/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef STOCK_EXCHANGE_DATA_H_
#define STOCK_EXCHANGE_DATA_H_
#include "../defines.h"
#include "../typedefs.h"
#include <list>

struct stock_exchange_data	//gielda material�w
{
    PLANET_DATA *		pPlanet;  /*!< planeta na kt�rej znajduje si� dana gie�da*/
	std::list<AUCTION_DATA*> auctions;
	std::list<AUCTION_DATA*> new_offers;
};

#endif //STOCK_EXCHANGE_DATA_H_

